version: '2'
services:
    lg-app:
        image: lg
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lg-postgresql:5432/lg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lg-postgresql:
        extends:
            file: postgresql.yml
            service: lg-postgresql
