version: '2'
services:
    lg-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/lg/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=lg
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
